global:
  domain: "" 

server:
  extraArgs:
    - --rootpath=/argocd  # Sets ArgoCD to serve under /argocd
    - --basehref=/argocd  # Sets the base URL to /argocd
    - --insecure          # Disables HTTP-to-HTTPS redirect, allowing HTTP
  ingress:
    enabled: true
    ingressClassName: alb  # Specifies the ALB Ingress controller
    annotations:
      alb.ingress.kubernetes.io/group.name: shared-group  # Groups with other Ingresses, adjust as needed
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/group.priority: "1" 
      alb.ingress.kubernetes.io/healthcheck-path: /argocd/healthz  # Health check path
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP         # Ensures HTTP is used
    
    path: /argocd
    pathType: Prefix  # Routes /argocd/* to ArgoCD service
    

  service:
    type: NodePort  # Default service type

config:
  params:
    server.insecure: true  # Disables HTTPS