apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.dbservice.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.dbservice.port | default 3306 }}
      targetPort: {{ .Values.dbservice.targetPort | default 3306 }}