apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaskops-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi